### PR TITLE
Remove the Instrument Addon from the list of recommended packages

### PR DESCRIPTION
**Pull request by rtzoeller**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-custom-device-virtual-package/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Removes https://github.com/ni/niveristand-instrument-addon-custom-device from the list of recommended packages.

### Why should this Pull Request be merged?

We are not shipping this as part of 20.2. This package can be added back once we are building for 20.3.

### What testing has been done?

N/A

### CODE REVIEW

**Comment by rtzoeller** [comment]
@buckd are we going to have issues with the packages for the instrument addon/FPGA addon being pulled in to the feed? IIRC that uses a blacklist of packages - should we be using a whitelist?

**Comment by rtzoeller** [comment]
FYI @bogdanp-ni. I can't add you as a reviewer because of permissions issues.

**Comment by buckd** [comment]
> @buckd are we going to have issues with the packages for the instrument addon/FPGA addon being pulled in to the feed? IIRC that uses a blacklist of packages - should we be using a whitelist?

Yes, we are currently pulling Instrument Addon into the 20.2 feed. The feed knows nothing about the virtual package. I can make it a whitelist.

**Comment by buckd** [comment]
@rtzoeller, @bogdanp-ni is now added as a collaborator and added as a reviewer.

**Pull request merged**
